// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAriotoI0xJdoIgEWu6xMWC7Wz-fr_eI_Y',
    appId: '1:972809671603:web:5521b213ce15d0e623b1c6',
    messagingSenderId: '972809671603',
    projectId: 'bags-5eec1',
    authDomain: 'bags-5eec1.firebaseapp.com',
    databaseURL: 'https://bags-5eec1-default-rtdb.firebaseio.com',
    storageBucket: 'bags-5eec1.firebasestorage.app',
    measurementId: 'G-H2CC6HCGJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN35sQs4PCrsQovQD3OvkQXgm_IaGZxjE',
    appId: '1:972809671603:android:ee27a84b0573c13a23b1c6',
    messagingSenderId: '972809671603',
    projectId: 'bags-5eec1',
    databaseURL: 'https://bags-5eec1-default-rtdb.firebaseio.com',
    storageBucket: 'bags-5eec1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArviWEe9LutgL_otP92Llnp0DyHivsRvw',
    appId: '1:972809671603:ios:80763fc56557e28423b1c6',
    messagingSenderId: '972809671603',
    projectId: 'bags-5eec1',
    databaseURL: 'https://bags-5eec1-default-rtdb.firebaseio.com',
    storageBucket: 'bags-5eec1.firebasestorage.app',
    androidClientId: '972809671603-6dhpn6i9l2eghqkj9lcu48va78iqarf1.apps.googleusercontent.com',
    iosClientId: '972809671603-s4n65iol08k1efcbda4dquv4p9iq10uf.apps.googleusercontent.com',
    iosBundleId: 'com.example.adminFoodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAriotoI0xJdoIgEWu6xMWC7Wz-fr_eI_Y',
    appId: '1:972809671603:web:45bce3089c75e34923b1c6',
    messagingSenderId: '972809671603',
    projectId: 'bags-5eec1',
    authDomain: 'bags-5eec1.firebaseapp.com',
    databaseURL: 'https://bags-5eec1-default-rtdb.firebaseio.com',
    storageBucket: 'bags-5eec1.firebasestorage.app',
    measurementId: 'G-D58Z7ZFTZZ',
  );
}
